# Generated by Django 5.1.3 on 2025-06-06 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overload_tracker_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Overload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Overload Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.PositiveIntegerField(default=0)),
                ('overload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overload_tracker_base.overload')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overload_tracker_base.workout')),
            ],
        ),
        migrations.AddField(
            model_name='overload',
            name='workouts',
            field=models.ManyToManyField(through='overload_tracker_base.WorkoutEntry', to='overload_tracker_base.workout'),
        ),
    ]
